# Generated by Django 2.2.1 on 2019-05-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190522_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
